#pragma once

const char* bsnes_gambatte_controller_json =
"{\n"
"\t\"buttons\":{\n"
"\t\t\"B\":{\"type\":\"button\", \"name\":\"B\"},\n"
"\t\t\"Y\":{\"type\":\"button\", \"name\":\"Y\"},\n"
"\t\t\"select\":{\"type\":\"button\", \"name\":\"select\", \"symbol\":\"s\"},\n"
"\t\t\"start\":{\"type\":\"button\", \"name\":\"start\", \"symbol\":\"S\"},\n"
"\t\t\"up\":{\"type\":\"button\", \"name\":\"up\", \"symbol\":\"\xE2\x86\x91\", \"macro\":\"^\", \"movie\":\"u\"},\n"
"\t\t\"down\":{\"type\":\"button\", \"name\":\"down\", \"symbol\":\"\xE2\x86\x93\", \"macro\":\"v\", \"movie\":\"d\"},\n"
"\t\t\"left\":{\"type\":\"button\", \"name\":\"left\", \"symbol\":\"\xE2\x86\x90\", \"macro\":\"<\", \"movie\":\"l\"},\n"
"\t\t\"right\":{\"type\":\"button\", \"name\":\"right\", \"symbol\":\"\xE2\x86\x92\", \"macro\":\">\", \"movie\":\"r\"},\n"
"\t\t\"A\":{\"type\":\"button\", \"name\":\"A\"},\n"
"\t\t\"X\":{\"type\":\"button\", \"name\":\"X\"},\n"
"\t\t\"L\":{\"type\":\"button\", \"name\":\"L\"},\n"
"\t\t\"R\":{\"type\":\"button\", \"name\":\"R\"},\n"
"\t\t\"ext0\":{\"type\":\"button\", \"name\":\"ext0\", \"symbol\":\"0\", \"macro\":\"E0\"},\n"
"\t\t\"ext1\":{\"type\":\"button\", \"name\":\"ext1\", \"symbol\":\"1\", \"macro\":\"E1\"},\n"
"\t\t\"ext2\":{\"type\":\"button\", \"name\":\"ext2\", \"symbol\":\"2\", \"macro\":\"E2\"},\n"
"\t\t\"ext3\":{\"type\":\"button\", \"name\":\"ext3\", \"symbol\":\"3\", \"macro\":\"E3\"},\n"
"\t\t\"trigger\":{\"type\":\"button\", \"name\":\"trigger\", \"symbol\":\"T\"},\n"
"\t\t\"cursor\":{\"type\":\"button\", \"name\":\"cursor\", \"symbol\":\"C\"},\n"
"\t\t\"turbo\":{\"type\":\"button\", \"name\":\"turbo\", \"symbol\":\"U\"},\n"
"\t\t\"pause\":{\"type\":\"button\", \"name\":\"pause\", \"symbol\":\"P\"},\n"
"\t\t\"xaxis\":{\"type\":\"lightgun\", \"name\":\"xaxis\", \"min\":-16, \"max\":271},\n"
"\t\t\"yaxis\":{\"type\":\"lightgun\", \"name\":\"yaxis\", \"min\":-16, \"max\":255},\n"
"\t\t\"xmotion\":{\"type\":\"raxis\", \"name\":\"xaxis\", \"min\":-255, \"max\":255, \"centers\":true},\n"
"\t\t\"ymotion\":{\"type\":\"raxis\", \"name\":\"yaxis\", \"min\":-255, \"max\":255, \"centers\":true},\n"
"\t\t\"framesync\":{\"type\":\"button\", \"name\":\"framesync\", \"symbol\":\"F\", \"shadow\":true},\n"
"\t\t\"reset\":{\"type\":\"button\", \"name\":\"reset\", \"symbol\":\"R\", \"shadow\":true},\n"
"\t\t\"hard\":{\"type\":\"button\", \"name\":\"hard\", \"symbol\":\"H\", \"shadow\":true},\n"
"\t\t\"rhigh\":{\"type\":\"axis\", \"name\":\"rhigh\", \"shadow\":true},\n"
"\t\t\"rlow\":{\"type\":\"axis\", \"name\":\"rlow\", \"shadow\":true},\n"
"\t\t\"shadownull\":{\"type\":\"null\", \"shadow\":true}\n"
"\t},\"controllers\":{\n"
"\t\t\"gamepad\":{\"type\":\"gamepad\", \"class\":\"gamepad\", \"buttons\":[\n"
"\t\t\t\"buttons/B\", \"buttons/Y\", \"buttons/select\", \"buttons/start\", \"buttons/up\", \"buttons/down\",\n"
"\t\t\t\"buttons/left\", \"buttons/right\", \"buttons/A\", \"buttons/X\", \"buttons/L\", \"buttons/R\"\n"
"\t\t]},\n"
"\t\t\"gamepad16\":{\"type\":\"gamepad16\", \"class\":\"gamepad\", \"buttons\":[\n"
"\t\t\t\"buttons/B\", \"buttons/Y\", \"buttons/select\", \"buttons/start\", \"buttons/up\", \"buttons/down\",\n"
"\t\t\t\"buttons/left\", \"buttons/right\", \"buttons/A\", \"buttons/X\", \"buttons/L\", \"buttons/R\",\n"
"\t\t\t\"buttons/ext0\", \"buttons/ext1\", \"buttons/ext2\", \"buttons/ext3\"\n"
"\t\t]},\n"
"\t\t\"justifier\":{\"type\":\"justifier\", \"class\":\"justifier\", \"buttons\":[\n"
"\t\t\t\"buttons/xaxis\", \"buttons/yaxis\", \"buttons/trigger\", \"buttons/start\"\n"
"\t\t]},\n"
"\t\t\"mouse\":{\"type\":\"mouse\", \"class\":\"mouse\", \"buttons\":[\n"
"\t\t\t\"buttons/xmotion\", \"buttons/ymotion\", \"buttons/L\", \"buttons/R\"\n"
"\t\t]},\n"
"\t\t\"superscope\":{\"type\":\"superscope\", \"class\":\"superscope\", \"buttons\":[\n"
"\t\t\t\"buttons/xaxis\", \"buttons/yaxis\", \"buttons/trigger\", \"buttons/cursor\", \"buttons/turbo\",\n"
"\t\t\t\"buttons/pause\"\n"
"\t\t]},\n"
"\t\t\"system\":{\"type\":\"(system)\", \"class\":\"(system)\", \"buttons\":[\n"
"\t\t\t\"buttons/framesync\", \"buttons/reset\", \"buttons/rhigh\", \"buttons/rlow\"\n"
"\t\t]},\n"
"\t\t\"system_hreset\":{\"type\":\"(system)\", \"class\":\"(system)\", \"buttons\":[\n"
"\t\t\t\"buttons/framesync\", \"buttons/reset\", \"buttons/rhigh\", \"buttons/rlow\", \"buttons/hard\"\n"
"\t\t]},\n"
"\t\t\"system_compact\":{\"type\":\"(system)\", \"class\":\"(system)\", \"buttons\":[\n"
"\t\t\t\"buttons/framesync\", \"buttons/reset\", \"buttons/shadownull\", \"buttons/shadownull\",\n"
"\t\t\t\"buttons/hard\"\n"
"\t\t]}\n"
"\t},\"ports\":[\n"
"\t\t{\"symbol\":\"none\", \"name\":\"none\", \"hname\":\"None\", \"controllers\":[],\"legal\":[1, 2]},\n"
"\t\t{\"symbol\":\"gamepad\", \"name\":\"gamepad\", \"hname\":\"gamepad\", \"controllers\":[\n"
"\t\t\t\"controllers/gamepad\"\n"
"\t\t],\"legal\":[1,2]},\n"
"\t\t{\"symbol\":\"gamepad16\", \"name\":\"gamepad16\", \"hname\":\"gamepad (16 buttons)\", \"controllers\":[\n"
"\t\t\t\"controllers/gamepad16\"\n"
"\t\t],\"legal\":[1,2]},\n"
"\t\t{\"symbol\":\"multitap\", \"name\":\"multitap\", \"hname\":\"Multitap\", \"controllers\":[\n"
"\t\t\t\"controllers/gamepad\", \"controllers/gamepad\", \"controllers/gamepad\", \"controllers/gamepad\"\n"
"\t\t],\"legal\":[1, 2]},\n"
"\t\t{\"symbol\":\"multitap16\", \"name\":\"multitap16\", \"hname\":\"Multitap (16 buttons)\", \"controllers\":[\n"
"\t\t\t\"controllers/gamepad16\", \"controllers/gamepad16\", \"controllers/gamepad16\",\n"
"\t\t\t\"controllers/gamepad16\"\n"
"\t\t],\"legal\":[1, 2]},\n"
"\t\t{\"symbol\":\"mouse\", \"name\":\"mouse\", \"hname\":\"Mouse\", \"controllers\":[\n"
"\t\t\t\"controllers/mouse\"\n"
"\t\t],\"legal\":[1, 2]},\n"
"\t\t{\"symbol\":\"justifier\", \"name\":\"justifier\", \"hname\":\"Justifier\", \"controllers\":[\n"
"\t\t\t\"controllers/justifier\"\n"
"\t\t],\"legal\":[2]},\n"
"\t\t{\"symbol\":\"justifiers\", \"name\":\"justifiers\", \"hname\":\"2 Justifiers\", \"controllers\":[\n"
"\t\t\t\"controllers/justifier\", \"controllers/justifier\"\n"
"\t\t],\"legal\":[2]},\n"
"\t\t{\"symbol\":\"superscope\", \"name\":\"superscope\", \"hname\":\"Super Scope\", \"controllers\":[\n"
"\t\t\t\"controllers/superscope\"\n"
"\t\t],\"legal\":[2]},\n"
"\t\t{\"symbol\":\"ygamepad16\", \"name\":\"ygamepad16\", \"hname\":\"Y-cabled gamepad (16 buttons)\", \"controllers\":[\n"
"\t\t\t\"controllers/gamepad16\", \"controllers/gamepad16\"\n"
"\t\t],\"legal\":[1,2]},\n"
"\t\t{\"symbol\":\"psystem\", \"name\":\"system\", \"hname\":\"system\", \"controllers\":[\n"
"\t\t\t\"controllers/system\"\n"
"\t\t],\"legal\":[0]},\n"
"\t\t{\"symbol\":\"psystem_hreset\", \"name\":\"system\", \"hname\":\"system\", \"controllers\":[\n"
"\t\t\t\"controllers/system_hreset\"\n"
"\t\t],\"legal\":[0]},\n"
"\t\t{\"symbol\":\"psystem_compact\", \"name\":\"system\", \"hname\":\"system\", \"controllers\":[\n"
"\t\t\t\"controllers/system_compact\"\n"
"\t\t],\"legal\":[0]}\n"
"\t],\"ports2\":[\n"
"\t\t{\"symbol\":\"psystem_compact2\", \"name\":\"system\", \"hname\":\"system\", \"controllers\":[\n"
"\t\t\t\"controllers/system_compact\"\n"
"\t\t],\"legal\":[0]},\n"
"\t\t{\"symbol\":\"gamepad2\", \"name\":\"gamepad\", \"hname\":\"gamepad\", \"controllers\":[\n"
"\t\t\t\"controllers/gamepad\"\n"
"\t\t],\"legal\":[1,2]}\n"
"\t]\n"
"}\n"
;