const char* lsnesrc_file =
	"bind-key /rctrl q quit-emulator\n"
	"bind-key rctrl/rctrl q quit-emulator /y\n"
	"bind-key pause pause-emulator\n"
	"alias-command +speed set-setting targetfps infinite\n"
	"alias-command -speed unset-setting targetfps\n"
	"bind-key scrollock +speed\n"
	"bind-key pageup scroll-up\n"
	"bind-key pagedown scroll-down\n"
	"bind-key home scroll-fullup\n"
	"bind-key end scroll-fulldown\n"
	"bind-key left +controller1left\n"
	"bind-key up +controller1up\n"
	"bind-key right +controller1right\n"
	"bind-key down +controller1down\n"
	"bind-key rctrl +controller1A\n"
	"bind-key ralt +controller1B\n"
	"bind-key rshift +controller1X\n"
	"bind-key l +controller1Y\n"
	"bind-key o +controller1L\n"
	"bind-key p +controller1R\n"
	"bind-key return +controller1start\n"
	"bind-key 0 +controller1select\n"
	"bind-key a +controller2left\n"
	"bind-key w +controller2up\n"
	"bind-key d +controller2right\n"
	"bind-key s +controller2down\n"
	"bind-key lctrl +controller2A\n"
	"bind-key lalt +controller2B\n"
	"bind-key lshift +controller2X\n"
	"bind-key z +controller2Y\n"
	"bind-key 1 +controller2L\n"
	"bind-key 3 +controller2R\n"
	"bind-key tab +controller2start\n"
	"bind-key x +controller2select\n"
	"bind-key backspace +advance-frame\n"
	"bind-key /shift f1 save-state movieslot1.lsmv\n"
	"bind-key /shift f2 save-state movieslot2.lsmv\n"
	"bind-key /shift f3 save-state movieslot3.lsmv\n"
	"bind-key /shift f4 save-state movieslot4.lsmv\n"
	"bind-key /shift f5 save-state movieslot5.lsmv\n"
	"bind-key /shift f6 save-state movieslot6.lsmv\n"
	"bind-key /shift f7 save-state movieslot7.lsmv\n"
	"bind-key /shift f8 save-state movieslot8.lsmv\n"
	"bind-key /shift f9 save-state movieslot9.lsmv\n"
	"bind-key /shift f10 save-state movieslota.lsmv\n"
	"bind-key /shift f11 save-state movieslotb.lsmv\n"
	"bind-key /shift f12 save-state movieslotc.lsmv\n"
	"bind-key shift/shift f1 load-state movieslot1.lsmv\n"
	"bind-key shift/shift f2 load-state movieslot2.lsmv\n"
	"bind-key shift/shift f3 load-state movieslot3.lsmv\n"
	"bind-key shift/shift f4 load-state movieslot4.lsmv\n"
	"bind-key shift/shift f5 load-state movieslot5.lsmv\n"
	"bind-key shift/shift f6 load-state movieslot6.lsmv\n"
	"bind-key shift/shift f7 load-state movieslot7.lsmv\n"
	"bind-key shift/shift f8 load-state movieslot8.lsmv\n"
	"bind-key shift/shift f9 load-state movieslot9.lsmv\n"
	"bind-key shift/shift f10 load-state movieslota.lsmv\n"
	"bind-key shift/shift f11 load-state movieslotb.lsmv\n"
	"bind-key shift/shift f12 load-state movieslotc.lsmv\n";
