#pragma once

struct lsnes_core_get_device_regs_reg snes_gb_registers[] = {
	{"scpu_pbpc", []() -> uint64_t { return SNES::cpu.regs.pc; }, [](uint64_t v) { SNES::cpu.regs.pc = v; }},
	{"scpu_pb", []() -> uint64_t { return SNES::cpu.regs.pc >> 16; },
		[](uint64_t v) { SNES::cpu.regs.pc = (v << 16) | (SNES::cpu.regs.pc & 0xFFFF); }},
	{"scpu_pc", []() -> uint64_t { return SNES::cpu.regs.pc & 0xFFFF; },
		[](uint64_t v) { SNES::cpu.regs.pc = (v & 0xFFFF) | (SNES::cpu.regs.pc & ~0xFFFF); }},
	{"scpu_r0", []() -> uint64_t { return SNES::cpu.regs.r[0]; }, [](uint64_t v) { SNES::cpu.regs.r[0] = v; }},
	{"scpu_r1", []() -> uint64_t { return SNES::cpu.regs.r[1]; }, [](uint64_t v) { SNES::cpu.regs.r[1] = v; }},
	{"scpu_r2", []() -> uint64_t { return SNES::cpu.regs.r[2]; }, [](uint64_t v) { SNES::cpu.regs.r[2] = v; }},
	{"scpu_r3", []() -> uint64_t { return SNES::cpu.regs.r[3]; }, [](uint64_t v) { SNES::cpu.regs.r[3] = v; }},
	{"scpu_r4", []() -> uint64_t { return SNES::cpu.regs.r[4]; }, [](uint64_t v) { SNES::cpu.regs.r[4] = v; }},
	{"scpu_r5", []() -> uint64_t { return SNES::cpu.regs.r[5]; }, [](uint64_t v) { SNES::cpu.regs.r[5] = v; }},
	{"scpu_a", []() -> uint64_t { return SNES::cpu.regs.a; }, [](uint64_t v) { SNES::cpu.regs.a = v; }},
	{"scpu_x", []() -> uint64_t { return SNES::cpu.regs.x; }, [](uint64_t v) { SNES::cpu.regs.x = v; }},
	{"scpu_y", []() -> uint64_t { return SNES::cpu.regs.y; }, [](uint64_t v) { SNES::cpu.regs.y = v; }},
	{"scpu_z", []() -> uint64_t { return SNES::cpu.regs.z; }, [](uint64_t v) { SNES::cpu.regs.z = v; }},
	{"scpu_s", []() -> uint64_t { return SNES::cpu.regs.s; }, [](uint64_t v) { SNES::cpu.regs.s = v; }},
	{"scpu_d", []() -> uint64_t { return SNES::cpu.regs.d; }, [](uint64_t v) { SNES::cpu.regs.d = v; }},
	{"scpu_db", []() -> uint64_t { return SNES::cpu.regs.db; }, [](uint64_t v) { SNES::cpu.regs.db = v; }},
	{"scpu_p", []() -> uint64_t { return SNES::cpu.regs.p; }, [](uint64_t v) { SNES::cpu.regs.p = v; }},
	{"scpu_e", []() -> uint64_t { return SNES::cpu.regs.e; }, [](uint64_t v) { SNES::cpu.regs.e = v; }},
	{"scpu_irq", []() -> uint64_t { return SNES::cpu.regs.irq; }, [](uint64_t v) { SNES::cpu.regs.irq = v; }},
	{"scpu_wai", []() -> uint64_t { return SNES::cpu.regs.wai; }, [](uint64_t v) { SNES::cpu.regs.wai = v; }},
	{"scpu_mdr", []() -> uint64_t { return SNES::cpu.regs.mdr; }, [](uint64_t v) { SNES::cpu.regs.mdr = v; }},
	{"scpu_vector", []() -> uint64_t { return SNES::cpu.regs.vector; },
		[](uint64_t v) { SNES::cpu.regs.vector = v; }},
	{"scpu_aa", []() -> uint64_t { return SNES::cpu.aa; }, [](uint64_t v) { SNES::cpu.aa = v; }},
	{"scpu_rd", []() -> uint64_t { return SNES::cpu.rd; }, [](uint64_t v) { SNES::cpu.rd = v; }},
	{"scpu_sp", []() -> uint64_t { return SNES::cpu.sp; }, [](uint64_t v) { SNES::cpu.sp = v; }},
	{"scpu_dp", []() -> uint64_t { return SNES::cpu.dp; }, [](uint64_t v) { SNES::cpu.dp = v; }},
	{"scpu_p_n", []() -> uint64_t { return SNES::cpu.regs.p.n; }, [](uint64_t v) { SNES::cpu.regs.p.n = v; },
		true},
	{"scpu_p_v", []() -> uint64_t { return SNES::cpu.regs.p.v; }, [](uint64_t v) { SNES::cpu.regs.p.v = v; },
		true},
	{"scpu_p_m", []() -> uint64_t { return SNES::cpu.regs.p.m; }, [](uint64_t v) { SNES::cpu.regs.p.m = v; },
		true},
	{"scpu_p_x", []() -> uint64_t { return SNES::cpu.regs.p.x; }, [](uint64_t v) { SNES::cpu.regs.p.x = v; },
		true},
	{"scpu_p_d", []() -> uint64_t { return SNES::cpu.regs.p.d; }, [](uint64_t v) { SNES::cpu.regs.p.d = v; },
		true},
	{"scpu_p_i", []() -> uint64_t { return SNES::cpu.regs.p.i; }, [](uint64_t v) { SNES::cpu.regs.p.i = v; },
		true},
	{"scpu_p_z", []() -> uint64_t { return SNES::cpu.regs.p.z; }, [](uint64_t v) { SNES::cpu.regs.p.z = v; },
		true},
	{"scpu_p_c", []() -> uint64_t { return SNES::cpu.regs.p.c; }, [](uint64_t v) { SNES::cpu.regs.p.c = v; },
		true},
	{"scpu_hcounter", []() -> uint64_t { return SNES::cpu.hcounter(); }, [](uint64_t v) {}, false},
	{"scpu_vcounter", []() -> uint64_t { return SNES::cpu.vcounter(); }, [](uint64_t v) {}, false},
	{"ppu_display_disabled", []() -> uint64_t { return SNES::ppu.regs.display_disabled; },
		[](uint64_t v) { SNES::ppu.regs.display_disabled = v; }, true},
	{"ppu_oam_priority", []() -> uint64_t { return SNES::ppu.regs.oam_priority; },
		[](uint64_t v) { SNES::ppu.regs.oam_priority = v; }, true},
	{"ppu_bg_tilesize[0]", []() -> uint64_t { return SNES::ppu.regs.bg_tilesize[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tilesize[0] = v; }, true},
	{"ppu_bg_tilesize[1]", []() -> uint64_t { return SNES::ppu.regs.bg_tilesize[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tilesize[1] = v; }, true},
	{"ppu_bg_tilesize[2]", []() -> uint64_t { return SNES::ppu.regs.bg_tilesize[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tilesize[2] = v; }, true},
	{"ppu_bg_tilesize[3]", []() -> uint64_t { return SNES::ppu.regs.bg_tilesize[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tilesize[3] = v; }, true},
	{"ppu_bg3_priority", []() -> uint64_t { return SNES::ppu.regs.bg3_priority; },
		[](uint64_t v) { SNES::ppu.regs.bg3_priority = v; }, true},
	{"ppu_mosaic_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.mosaic_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.mosaic_enabled[0] = v; }, true},
	{"ppu_mosaic_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.mosaic_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.mosaic_enabled[1] = v; }, true},
	{"ppu_mosaic_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.mosaic_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.mosaic_enabled[2] = v; }, true},
	{"ppu_mosaic_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.mosaic_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.mosaic_enabled[3] = v; }, true},
	{"ppu_vram_incmode", []() -> uint64_t { return SNES::ppu.regs.vram_incmode; },
		[](uint64_t v) { SNES::ppu.regs.vram_incmode = v; }, true},
	{"ppu_mode7_vflip", []() -> uint64_t { return SNES::ppu.regs.mode7_vflip; },
		[](uint64_t v) { SNES::ppu.regs.mode7_vflip = v; }, true},
	{"ppu_mode7_hflip", []() -> uint64_t { return SNES::ppu.regs.mode7_hflip; },
		[](uint64_t v) { SNES::ppu.regs.mode7_hflip = v; }, true},
	{"ppu_window1_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.window1_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.window1_enabled[0] = v; }, true},
	{"ppu_window1_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.window1_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.window1_enabled[1] = v; }, true},
	{"ppu_window1_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.window1_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.window1_enabled[2] = v; }, true},
	{"ppu_window1_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.window1_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.window1_enabled[3] = v; }, true},
	{"ppu_window1_enabled[4]", []() -> uint64_t { return SNES::ppu.regs.window1_enabled[4]; },
		[](uint64_t v) { SNES::ppu.regs.window1_enabled[4] = v; }, true},
	{"ppu_window1_enabled[5]", []() -> uint64_t { return SNES::ppu.regs.window1_enabled[5]; },
		[](uint64_t v) { SNES::ppu.regs.window1_enabled[5] = v; }, true},
	{"ppu_window1_invert[0]", []() -> uint64_t { return SNES::ppu.regs.window1_invert[0]; },
		[](uint64_t v) { SNES::ppu.regs.window1_invert[0] = v; }, true},
	{"ppu_window1_invert[1]", []() -> uint64_t { return SNES::ppu.regs.window1_invert[1]; },
		[](uint64_t v) { SNES::ppu.regs.window1_invert[1] = v; }, true},
	{"ppu_window1_invert[2]", []() -> uint64_t { return SNES::ppu.regs.window1_invert[2]; },
		[](uint64_t v) { SNES::ppu.regs.window1_invert[2] = v; }, true},
	{"ppu_window1_invert[3]", []() -> uint64_t { return SNES::ppu.regs.window1_invert[3]; },
		[](uint64_t v) { SNES::ppu.regs.window1_invert[3] = v; }, true},
	{"ppu_window1_invert[4]", []() -> uint64_t { return SNES::ppu.regs.window1_invert[4]; },
		[](uint64_t v) { SNES::ppu.regs.window1_invert[4] = v; }, true},
	{"ppu_window1_invert[5]", []() -> uint64_t { return SNES::ppu.regs.window1_invert[5]; },
		[](uint64_t v) { SNES::ppu.regs.window1_invert[5] = v; }, true},
	{"ppu_window2_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.window2_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.window2_enabled[0] = v; }, true},
	{"ppu_window2_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.window2_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.window2_enabled[1] = v; }, true},
	{"ppu_window2_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.window2_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.window2_enabled[2] = v; }, true},
	{"ppu_window2_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.window2_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.window2_enabled[3] = v; }, true},
	{"ppu_window2_enabled[4]", []() -> uint64_t { return SNES::ppu.regs.window2_enabled[4]; },
		[](uint64_t v) { SNES::ppu.regs.window2_enabled[4] = v; }, true},
	{"ppu_window2_enabled[5]", []() -> uint64_t { return SNES::ppu.regs.window2_enabled[5]; },
		[](uint64_t v) { SNES::ppu.regs.window2_enabled[5] = v; }, true},
	{"ppu_window2_invert[0]", []() -> uint64_t { return SNES::ppu.regs.window2_invert[0]; },
		[](uint64_t v) { SNES::ppu.regs.window2_invert[0] = v; }, true},
	{"ppu_window2_invert[1]", []() -> uint64_t { return SNES::ppu.regs.window2_invert[1]; },
		[](uint64_t v) { SNES::ppu.regs.window2_invert[1] = v; }, true},
	{"ppu_window2_invert[2]", []() -> uint64_t { return SNES::ppu.regs.window2_invert[2]; },
		[](uint64_t v) { SNES::ppu.regs.window2_invert[2] = v; }, true},
	{"ppu_window2_invert[3]", []() -> uint64_t { return SNES::ppu.regs.window2_invert[3]; },
		[](uint64_t v) { SNES::ppu.regs.window2_invert[3] = v; }, true},
	{"ppu_window2_invert[4]", []() -> uint64_t { return SNES::ppu.regs.window2_invert[4]; },
		[](uint64_t v) { SNES::ppu.regs.window2_invert[4] = v; }, true},
	{"ppu_window2_invert[5]", []() -> uint64_t { return SNES::ppu.regs.window2_invert[5]; },
		[](uint64_t v) { SNES::ppu.regs.window2_invert[5] = v; }, true},
	{"ppu_bg_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.bg_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_enabled[0] = v; }, true},
	{"ppu_bg_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.bg_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_enabled[1] = v; }, true},
	{"ppu_bg_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.bg_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_enabled[2] = v; }, true},
	{"ppu_bg_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.bg_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_enabled[3] = v; }, true},
	{"ppu_bg_enabled[4]", []() -> uint64_t { return SNES::ppu.regs.bg_enabled[4]; },
		[](uint64_t v) { SNES::ppu.regs.bg_enabled[4] = v; }, true},
	{"ppu_bgsub_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.bgsub_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.bgsub_enabled[0] = v; }, true},
	{"ppu_bgsub_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.bgsub_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.bgsub_enabled[1] = v; }, true},
	{"ppu_bgsub_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.bgsub_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.bgsub_enabled[2] = v; }, true},
	{"ppu_bgsub_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.bgsub_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.bgsub_enabled[3] = v; }, true},
	{"ppu_bgsub_enabled[4]", []() -> uint64_t { return SNES::ppu.regs.bgsub_enabled[4]; },
		[](uint64_t v) { SNES::ppu.regs.bgsub_enabled[4] = v; }, true},
	{"ppu_window_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.window_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.window_enabled[0] = v; }, true},
	{"ppu_window_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.window_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.window_enabled[1] = v; }, true},
	{"ppu_window_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.window_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.window_enabled[2] = v; }, true},
	{"ppu_window_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.window_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.window_enabled[3] = v; }, true},
	{"ppu_window_enabled[4]", []() -> uint64_t { return SNES::ppu.regs.window_enabled[4]; },
		[](uint64_t v) { SNES::ppu.regs.window_enabled[4] = v; }, true},
	{"ppu_sub_window_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.sub_window_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.sub_window_enabled[0] = v; }, true},
	{"ppu_sub_window_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.sub_window_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.sub_window_enabled[1] = v; }, true},
	{"ppu_sub_window_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.sub_window_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.sub_window_enabled[2] = v; }, true},
	{"ppu_sub_window_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.sub_window_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.sub_window_enabled[3] = v; }, true},
	{"ppu_sub_window_enabled[4]", []() -> uint64_t { return SNES::ppu.regs.sub_window_enabled[4]; },
		[](uint64_t v) { SNES::ppu.regs.sub_window_enabled[4] = v; }, true},
	{"ppu_addsub_mode", []() -> uint64_t { return SNES::ppu.regs.addsub_mode; },
		[](uint64_t v) { SNES::ppu.regs.addsub_mode = v; }, true},
	{"ppu_direct_color", []() -> uint64_t { return SNES::ppu.regs.direct_color; },
		[](uint64_t v) { SNES::ppu.regs.direct_color = v; }, true},
	{"ppu_color_mode", []() -> uint64_t { return SNES::ppu.regs.color_mode; },
		[](uint64_t v) { SNES::ppu.regs.color_mode = v; }, true},
	{"ppu_color_halve", []() -> uint64_t { return SNES::ppu.regs.color_halve; },
		[](uint64_t v) { SNES::ppu.regs.color_halve = v; }, true},
	{"ppu_color_enabled[0]", []() -> uint64_t { return SNES::ppu.regs.color_enabled[0]; },
		[](uint64_t v) { SNES::ppu.regs.color_enabled[0] = v; }, true},
	{"ppu_color_enabled[1]", []() -> uint64_t { return SNES::ppu.regs.color_enabled[1]; },
		[](uint64_t v) { SNES::ppu.regs.color_enabled[1] = v; }, true},
	{"ppu_color_enabled[2]", []() -> uint64_t { return SNES::ppu.regs.color_enabled[2]; },
		[](uint64_t v) { SNES::ppu.regs.color_enabled[2] = v; }, true},
	{"ppu_color_enabled[3]", []() -> uint64_t { return SNES::ppu.regs.color_enabled[3]; },
		[](uint64_t v) { SNES::ppu.regs.color_enabled[3] = v; }, true},
	{"ppu_color_enabled[4]", []() -> uint64_t { return SNES::ppu.regs.color_enabled[4]; },
		[](uint64_t v) { SNES::ppu.regs.color_enabled[4] = v; }, true},
	{"ppu_color_enabled[5]", []() -> uint64_t { return SNES::ppu.regs.color_enabled[5]; },
		[](uint64_t v) { SNES::ppu.regs.color_enabled[5] = v; }, true},
	{"ppu_mode7_extbg", []() -> uint64_t { return SNES::ppu.regs.mode7_extbg; },
		[](uint64_t v) { SNES::ppu.regs.mode7_extbg = v; }, true},
	{"ppu_pseudo_hires", []() -> uint64_t { return SNES::ppu.regs.pseudo_hires; },
		[](uint64_t v) { SNES::ppu.regs.pseudo_hires = v; }, true},
	{"ppu_overscan", []() -> uint64_t { return SNES::ppu.regs.overscan; },
		[](uint64_t v) { SNES::ppu.regs.overscan = v; }, true},
	{"ppu_oam_interlace", []() -> uint64_t { return SNES::ppu.regs.oam_interlace; },
		[](uint64_t v) { SNES::ppu.regs.oam_interlace = v; }, true},
	{"ppu_interlace", []() -> uint64_t { return SNES::ppu.regs.interlace; },
		[](uint64_t v) { SNES::ppu.regs.interlace = v; }, true},
	{"ppu_latch_hcounter", []() -> uint64_t { return SNES::ppu.regs.latch_hcounter; },
		[](uint64_t v) { SNES::ppu.regs.latch_hcounter = v; }, true},
	{"ppu_latch_vcounter", []() -> uint64_t { return SNES::ppu.regs.latch_vcounter; },
		[](uint64_t v) { SNES::ppu.regs.latch_vcounter = v; }, true},
	{"ppu_counters_latched", []() -> uint64_t { return SNES::ppu.regs.counters_latched; },
		[](uint64_t v) { SNES::ppu.regs.counters_latched = v; }, true},
	{"ppu_time_over", []() -> uint64_t { return SNES::ppu.regs.time_over; },
		[](uint64_t v) { SNES::ppu.regs.time_over = v; }, true},
	{"ppu_range_over", []() -> uint64_t { return SNES::ppu.regs.range_over; },
		[](uint64_t v) { SNES::ppu.regs.range_over = v; }, true},
	{"ppu_ppu1_mdr", []() -> uint64_t { return SNES::ppu.regs.ppu1_mdr; },
		[](uint64_t v) { SNES::ppu.regs.ppu1_mdr = v; }},
	{"ppu_ppu2_mdr", []() -> uint64_t { return SNES::ppu.regs.ppu2_mdr; },
		[](uint64_t v) { SNES::ppu.regs.ppu2_mdr = v; }},
	{"ppu_bg_y[0]", []() -> uint64_t { return SNES::ppu.regs.bg_y[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_y[0] = v; }},
	{"ppu_bg_y[1]", []() -> uint64_t { return SNES::ppu.regs.bg_y[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_y[1] = v; }},
	{"ppu_bg_y[2]", []() -> uint64_t { return SNES::ppu.regs.bg_y[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_y[2] = v; }},
	{"ppu_bg_y[3]", []() -> uint64_t { return SNES::ppu.regs.bg_y[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_y[3] = v; }},
	{"ppu_ioamaddr", []() -> uint64_t { return SNES::ppu.regs.ioamaddr; },
		[](uint64_t v) { SNES::ppu.regs.ioamaddr = v; }},
	{"ppu_icgramaddr", []() -> uint64_t { return SNES::ppu.regs.icgramaddr; },
		[](uint64_t v) { SNES::ppu.regs.icgramaddr = v; }},
	{"ppu_display_brightness", []() -> uint64_t { return SNES::ppu.regs.display_brightness; },
		[](uint64_t v) { SNES::ppu.regs.display_brightness = v; }},
	{"ppu_oam_basesize", []() -> uint64_t { return SNES::ppu.regs.oam_basesize; },
		[](uint64_t v) { SNES::ppu.regs.oam_basesize = v; }},
	{"ppu_oam_nameselect", []() -> uint64_t { return SNES::ppu.regs.oam_nameselect; },
		[](uint64_t v) { SNES::ppu.regs.oam_nameselect = v; }},
	{"ppu_oam_tdaddr", []() -> uint64_t { return SNES::ppu.regs.oam_tdaddr; },
		[](uint64_t v) { SNES::ppu.regs.oam_tdaddr = v; }},
	{"ppu_oam_baseaddr", []() -> uint64_t { return SNES::ppu.regs.oam_baseaddr; },
		[](uint64_t v) { SNES::ppu.regs.oam_baseaddr = v; }},
	{"ppu_oam_addr", []() -> uint64_t { return SNES::ppu.regs.oam_addr; },
		[](uint64_t v) { SNES::ppu.regs.oam_addr = v; }},
	{"ppu_oam_firstsprite", []() -> uint64_t { return SNES::ppu.regs.oam_firstsprite; },
		[](uint64_t v) { SNES::ppu.regs.oam_firstsprite = v; }},
	{"ppu_oam_latchdata", []() -> uint64_t { return SNES::ppu.regs.oam_latchdata; },
		[](uint64_t v) { SNES::ppu.regs.oam_latchdata = v; }},
	{"ppu_bg_mode", []() -> uint64_t { return SNES::ppu.regs.bg_mode; },
		[](uint64_t v) { SNES::ppu.regs.bg_mode = v; }},
	{"ppu_mosaic_size", []() -> uint64_t { return SNES::ppu.regs.mosaic_size; },
		[](uint64_t v) { SNES::ppu.regs.mosaic_size = v; }},
	{"ppu_mosaic_countdown", []() -> uint64_t { return SNES::ppu.regs.mosaic_countdown; },
		[](uint64_t v) { SNES::ppu.regs.mosaic_countdown = v; }},
	{"ppu_bg_scaddr[0]", []() -> uint64_t { return SNES::ppu.regs.bg_scaddr[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scaddr[0] = v; }},
	{"ppu_bg_scaddr[1]", []() -> uint64_t { return SNES::ppu.regs.bg_scaddr[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scaddr[1] = v; }},
	{"ppu_bg_scaddr[2]", []() -> uint64_t { return SNES::ppu.regs.bg_scaddr[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scaddr[2] = v; }},
	{"ppu_bg_scaddr[3]", []() -> uint64_t { return SNES::ppu.regs.bg_scaddr[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scaddr[3] = v; }},
	{"ppu_bg_scsize[0]", []() -> uint64_t { return SNES::ppu.regs.bg_scsize[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scsize[0] = v; }},
	{"ppu_bg_scsize[1]", []() -> uint64_t { return SNES::ppu.regs.bg_scsize[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scsize[1] = v; }},
	{"ppu_bg_scsize[2]", []() -> uint64_t { return SNES::ppu.regs.bg_scsize[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scsize[2] = v; }},
	{"ppu_bg_scsize[3]", []() -> uint64_t { return SNES::ppu.regs.bg_scsize[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_scsize[3] = v; }},
	{"ppu_bg_tdaddr[0]", []() -> uint64_t { return SNES::ppu.regs.bg_tdaddr[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tdaddr[0] = v; }},
	{"ppu_bg_tdaddr[1]", []() -> uint64_t { return SNES::ppu.regs.bg_tdaddr[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tdaddr[1] = v; }},
	{"ppu_bg_tdaddr[2]", []() -> uint64_t { return SNES::ppu.regs.bg_tdaddr[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tdaddr[2] = v; }},
	{"ppu_bg_tdaddr[3]", []() -> uint64_t { return SNES::ppu.regs.bg_tdaddr[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_tdaddr[3] = v; }},
	{"ppu_bg_ofslatch", []() -> uint64_t { return SNES::ppu.regs.bg_ofslatch; },
		[](uint64_t v) { SNES::ppu.regs.bg_ofslatch = v; }},
	{"ppu_m7_hofs", []() -> uint64_t { return SNES::ppu.regs.m7_hofs; },
		[](uint64_t v) { SNES::ppu.regs.m7_hofs = v; }},
	{"ppu_m7_vofs", []() -> uint64_t { return SNES::ppu.regs.m7_vofs; },
		[](uint64_t v) { SNES::ppu.regs.m7_vofs = v; }},
	{"ppu_bg_hofs[0]", []() -> uint64_t { return SNES::ppu.regs.bg_hofs[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_hofs[0] = v; }},
	{"ppu_bg_hofs[1]", []() -> uint64_t { return SNES::ppu.regs.bg_hofs[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_hofs[1] = v; }},
	{"ppu_bg_hofs[2]", []() -> uint64_t { return SNES::ppu.regs.bg_hofs[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_hofs[2] = v; }},
	{"ppu_bg_hofs[3]", []() -> uint64_t { return SNES::ppu.regs.bg_hofs[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_hofs[3] = v; }},
	{"ppu_bg_vofs[0]", []() -> uint64_t { return SNES::ppu.regs.bg_vofs[0]; },
		[](uint64_t v) { SNES::ppu.regs.bg_vofs[0] = v; }},
	{"ppu_bg_vofs[1]", []() -> uint64_t { return SNES::ppu.regs.bg_vofs[1]; },
		[](uint64_t v) { SNES::ppu.regs.bg_vofs[1] = v; }},
	{"ppu_bg_vofs[2]", []() -> uint64_t { return SNES::ppu.regs.bg_vofs[2]; },
		[](uint64_t v) { SNES::ppu.regs.bg_vofs[2] = v; }},
	{"ppu_bg_vofs[3]", []() -> uint64_t { return SNES::ppu.regs.bg_vofs[3]; },
		[](uint64_t v) { SNES::ppu.regs.bg_vofs[3] = v; }},
	{"ppu_vram_mapping", []() -> uint64_t { return SNES::ppu.regs.vram_mapping; },
		[](uint64_t v) { SNES::ppu.regs.vram_mapping = v; }},
	{"ppu_vram_incsize", []() -> uint64_t { return SNES::ppu.regs.vram_incsize; },
		[](uint64_t v) { SNES::ppu.regs.vram_incsize = v; }},
	{"ppu_vram_addr", []() -> uint64_t { return SNES::ppu.regs.vram_addr; },
		[](uint64_t v) { SNES::ppu.regs.vram_addr = v; }},
	{"ppu_mode7_repeat", []() -> uint64_t { return SNES::ppu.regs.mode7_repeat; },
		[](uint64_t v) { SNES::ppu.regs.mode7_repeat = v; }},
	{"ppu_m7_latch", []() -> uint64_t { return SNES::ppu.regs.m7_latch; },
		[](uint64_t v) { SNES::ppu.regs.m7_latch = v; }},
	{"ppu_m7a", []() -> uint64_t { return SNES::ppu.regs.m7a; },
		[](uint64_t v) { SNES::ppu.regs.m7a = v; }},
	{"ppu_m7b", []() -> uint64_t { return SNES::ppu.regs.m7b; },
		[](uint64_t v) { SNES::ppu.regs.m7b = v; }},
	{"ppu_m7c", []() -> uint64_t { return SNES::ppu.regs.m7c; },
		[](uint64_t v) { SNES::ppu.regs.m7c = v; }},
	{"ppu_m7d", []() -> uint64_t { return SNES::ppu.regs.m7d; },
		[](uint64_t v) { SNES::ppu.regs.m7d = v; }},
	{"ppu_m7x", []() -> uint64_t { return SNES::ppu.regs.m7x; },
		[](uint64_t v) { SNES::ppu.regs.m7x = v; }},
	{"ppu_m7y", []() -> uint64_t { return SNES::ppu.regs.m7y; },
		[](uint64_t v) { SNES::ppu.regs.m7y = v; }},
	{"ppu_cgram_addr", []() -> uint64_t { return SNES::ppu.regs.cgram_addr; },
		[](uint64_t v) { SNES::ppu.regs.cgram_addr = v; }},
	{"ppu_cgram_latchdata", []() -> uint64_t { return SNES::ppu.regs.cgram_latchdata; },
		[](uint64_t v) { SNES::ppu.regs.cgram_latchdata = v; }},
	{"ppu_window1_left", []() -> uint64_t { return SNES::ppu.regs.window1_left; },
		[](uint64_t v) { SNES::ppu.regs.window1_left = v; }},
	{"ppu_window1_right", []() -> uint64_t { return SNES::ppu.regs.window1_right; },
		[](uint64_t v) { SNES::ppu.regs.window1_right = v; }},
	{"ppu_window2_left", []() -> uint64_t { return SNES::ppu.regs.window2_left; },
		[](uint64_t v) { SNES::ppu.regs.window2_left = v; }},
	{"ppu_window2_right", []() -> uint64_t { return SNES::ppu.regs.window2_right; },
		[](uint64_t v) { SNES::ppu.regs.window2_right = v; }},
	{"ppu_window_mask[0]", []() -> uint64_t { return SNES::ppu.regs.window_mask[0]; },
		[](uint64_t v) { SNES::ppu.regs.window_mask[0] = v; }},
	{"ppu_window_mask[1]", []() -> uint64_t { return SNES::ppu.regs.window_mask[1]; },
		[](uint64_t v) { SNES::ppu.regs.window_mask[1] = v; }},
	{"ppu_window_mask[2]", []() -> uint64_t { return SNES::ppu.regs.window_mask[2]; },
		[](uint64_t v) { SNES::ppu.regs.window_mask[2] = v; }},
	{"ppu_window_mask[3]", []() -> uint64_t { return SNES::ppu.regs.window_mask[3]; },
		[](uint64_t v) { SNES::ppu.regs.window_mask[3] = v; }},
	{"ppu_window_mask[4]", []() -> uint64_t { return SNES::ppu.regs.window_mask[4]; },
		[](uint64_t v) { SNES::ppu.regs.window_mask[4] = v; }},
	{"ppu_window_mask[5]", []() -> uint64_t { return SNES::ppu.regs.window_mask[5]; },
		[](uint64_t v) { SNES::ppu.regs.window_mask[5] = v; }},
	{"ppu_color_mask", []() -> uint64_t { return SNES::ppu.regs.color_mask; },
		[](uint64_t v) { SNES::ppu.regs.color_mask = v; }},
	{"ppu_colorsub_mask", []() -> uint64_t { return SNES::ppu.regs.colorsub_mask; },
		[](uint64_t v) { SNES::ppu.regs.colorsub_mask = v; }},
	{"ppu_color_r", []() -> uint64_t { return SNES::ppu.regs.color_r; },
		[](uint64_t v) { SNES::ppu.regs.color_r = v; }},
	{"ppu_color_g", []() -> uint64_t { return SNES::ppu.regs.color_g; },
		[](uint64_t v) { SNES::ppu.regs.color_g = v; }},
	{"ppu_color_b", []() -> uint64_t { return SNES::ppu.regs.color_b; },
		[](uint64_t v) { SNES::ppu.regs.color_b = v; }},
	{"ppu_color_rgb", []() -> uint64_t { return SNES::ppu.regs.color_rgb; },
		[](uint64_t v) { SNES::ppu.regs.color_rgb = v; }},
	{"ppu_scanlines", []() -> uint64_t { return SNES::ppu.regs.scanlines; },
		[](uint64_t v) { SNES::ppu.regs.scanlines = v; }},
	{"ppu_hcounter", []() -> uint64_t { return SNES::ppu.regs.hcounter; },
		[](uint64_t v) { SNES::ppu.regs.hcounter = v; }},
	{"ppu_vcounter", []() -> uint64_t { return SNES::ppu.regs.vcounter; },
		[](uint64_t v) { SNES::ppu.regs.vcounter = v; }},
	{"ppu_vram_readbuffer", []() -> uint64_t { return SNES::ppu.regs.vram_readbuffer; },
		[](uint64_t v) { SNES::ppu.regs.vram_readbuffer = v; }},
	{"ppu_oam_itemcount", []() -> uint64_t { return SNES::ppu.regs.oam_itemcount; },
		[](uint64_t v) { SNES::ppu.regs.oam_itemcount = v; }},
	{"ppu_oam_tilecount", []() -> uint64_t { return SNES::ppu.regs.oam_tilecount; },
		[](uint64_t v) { SNES::ppu.regs.oam_tilecount = v; }},
	{"gb_wrambank", []() -> uint64_t { return gb_instance ? gb_instance->getIoRam().first[0x170] & 0x07 : 0; },
		[](uint64_t v) {}},
	{"gb_cyclecount", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_CYCLECOUNTER); },
		[](uint64_t v) {}},
	{"gb_pc", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_PC); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_PC, v); }},
	{"gb_sp", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_SP); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_SP, v); }},
	{"gb_hf1", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_HF1); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_HF1, v); }},
	{"gb_hf2", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_HF2); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_HF2, v); }},
	{"gb_zf", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_ZF); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_ZF, v); }},
	{"gb_cf", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_CF); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_CF, v); }},
	{"gb_a", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_A); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_A, v); }},
	{"gb_b", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_B); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_B, v); }},
	{"gb_c", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_C); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_C, v); }},
	{"gb_d", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_D); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_D, v); }},
	{"gb_e", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_E); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_E, v); }},
	{"gb_f", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_F); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_F, v); }},
	{"gb_h", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_H); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_H, v); }},
	{"gb_l", []() -> uint64_t { return gb_instance->get_cpureg(gambatte::GB::REG_L); },
		[](uint64_t v) { gb_instance->set_cpureg(gambatte::GB::REG_L, v); }},
	{"gb_tsc", []() -> uint64_t { return gb_tsc; },
		[](uint64_t v) {}},
	{"sgb_fdiv", []() -> uint64_t { return SNES::icd2.fdiv; },
		[](uint64_t v) {}},
	{"smp_pc", []() -> uint64_t { return SNES::smp.regs.pc; }, [](uint64_t v) { SNES::smp.regs.pc = v; }},
	{"smp_ya", []() -> uint64_t { return SNES::smp.regs.ya; }, [](uint64_t v) { SNES::smp.regs.ya = v; }},
	{"smp_y", []() -> uint64_t { return SNES::smp.regs.y; }, [](uint64_t v) { SNES::smp.regs.y = v; }},
	{"smp_a", []() -> uint64_t { return SNES::smp.regs.a; }, [](uint64_t v) { SNES::smp.regs.a = v; }},
	{"smp_x", []() -> uint64_t { return SNES::smp.regs.x; }, [](uint64_t v) { SNES::smp.regs.x = v; }},
	{"smp_s", []() -> uint64_t { return SNES::smp.regs.s; }, [](uint64_t v) { SNES::smp.regs.s = v; }},
	{"smp_p", []() -> uint64_t { return SNES::smp.regs.p; }, [](uint64_t v) { SNES::smp.regs.p = v; }},
	{"smp_p_n", []() -> uint64_t { return SNES::smp.regs.p.n; }, [](uint64_t v) { SNES::smp.regs.p.n = v; },
		true},
	{"smp_p_v", []() -> uint64_t { return SNES::smp.regs.p.v; }, [](uint64_t v) { SNES::smp.regs.p.v = v; },
		true},
	{"smp_p_p", []() -> uint64_t { return SNES::smp.regs.p.p; }, [](uint64_t v) { SNES::smp.regs.p.v = v; },
		true},
	{"smp_p_b", []() -> uint64_t { return SNES::smp.regs.p.b; }, [](uint64_t v) { SNES::smp.regs.p.b = v; },
		true},
	{"smp_p_h", []() -> uint64_t { return SNES::smp.regs.p.h; }, [](uint64_t v) { SNES::smp.regs.p.h = v; },
		true},
	{"smp_p_i", []() -> uint64_t { return SNES::smp.regs.p.i; }, [](uint64_t v) { SNES::smp.regs.p.i = v; },
		true},
	{"smp_p_z", []() -> uint64_t { return SNES::smp.regs.p.z; }, [](uint64_t v) { SNES::smp.regs.p.z = v; },
		true},
	{"smp_p_c", []() -> uint64_t { return SNES::smp.regs.p.c; }, [](uint64_t v) { SNES::smp.regs.p.c = v; },
		true},
	{"smp_dp_w", []() -> uint64_t { return SNES::smp.dp.w; }, [](uint64_t v) { SNES::smp.dp.w = v; }},
	{"smp_dp_l", []() -> uint64_t { return SNES::smp.dp.l; }, [](uint64_t v) { SNES::smp.dp.l = v; }},
	{"smp_dp_h", []() -> uint64_t { return SNES::smp.dp.h; }, [](uint64_t v) { SNES::smp.dp.h = v; }},
	{"smp_sp_w", []() -> uint64_t { return SNES::smp.sp.w; }, [](uint64_t v) { SNES::smp.sp.w = v; }},
	{"smp_sp_l", []() -> uint64_t { return SNES::smp.sp.l; }, [](uint64_t v) { SNES::smp.sp.l = v; }},
	{"smp_sp_h", []() -> uint64_t { return SNES::smp.sp.h; }, [](uint64_t v) { SNES::smp.sp.h = v; }},
	{"smp_rd_w", []() -> uint64_t { return SNES::smp.rd.w; }, [](uint64_t v) { SNES::smp.rd.w = v; }},
	{"smp_rd_l", []() -> uint64_t { return SNES::smp.rd.l; }, [](uint64_t v) { SNES::smp.rd.l = v; }},
	{"smp_rd_h", []() -> uint64_t { return SNES::smp.rd.h; }, [](uint64_t v) { SNES::smp.rd.h = v; }},
	{"smp_wr_w", []() -> uint64_t { return SNES::smp.wr.w; }, [](uint64_t v) { SNES::smp.wr.w = v; }},
	{"smp_wr_l", []() -> uint64_t { return SNES::smp.wr.l; }, [](uint64_t v) { SNES::smp.wr.l = v; }},
	{"smp_wr_h", []() -> uint64_t { return SNES::smp.wr.h; }, [](uint64_t v) { SNES::smp.wr.h = v; }},
	{"smp_bit_w", []() -> uint64_t { return SNES::smp.bit.w; }, [](uint64_t v) { SNES::smp.bit.w = v; }},
	{"smp_bit_l", []() -> uint64_t { return SNES::smp.bit.l; }, [](uint64_t v) { SNES::smp.bit.l = v; }},
	{"smp_bit_h", []() -> uint64_t { return SNES::smp.bit.h; }, [](uint64_t v) { SNES::smp.bit.h = v; }},
	{"smp_ya_w", []() -> uint64_t { return SNES::smp.ya.w; }, [](uint64_t v) { SNES::smp.ya.w = v; }},
	{"smp_ya_l", []() -> uint64_t { return SNES::smp.ya.l; }, [](uint64_t v) { SNES::smp.ya.l = v; }},
	{"smp_ya_h", []() -> uint64_t { return SNES::smp.ya.h; }, [](uint64_t v) { SNES::smp.ya.h = v; }},
	//DSP registers, chip registers.
	{NULL, NULL, NULL}
};
